# ACTIONS IDS
ID_STOP, ID_MOVE, ID_ATTACK, ID_ATTACK_MOVE,  ID_TRAIN,  ID_HARVEST = range(6)

# UNIT TYPE IDS
ID_UNIT = 50
ID_BUILDING = 51
ID_NEUTRALSTUFF = 52
ID_HARVESTER = 53
ID_MINERAL = 54
ID_GAS = 55
ID_WAREHOUSE = 56 # RESOURSE RECEPTION

# ATTACK DAMAGE TYPES
ID_BLUDGEONING, ID_PIERCING, ID_SLASHING, ID_FIRE = range(100, 104)

# UNITS
ID_MINERAL_PATCH = 150
ID_NEXUS = 170
ID_TURRET = 171
ID_WORKER = 200
ID_RANGED = 201
ID_TANK = 202
