# ACTIONS IDS
ID_STOP, ID_MOVE, ID_ATTACK, ID_ATTACK_MOVE,  ID_TRAIN = range(5)

# UNIT TYPE IDS
ID_UNIT, ID_BUILDING, ID_NEUTRALSTUFF  = range(50, 53)

# ATTACK DAMAGE TYPES
ID_BLUDGEONING, ID_PIERCING, ID_SLASHING, ID_FIRE = range(100, 104)

# NEUTRAL STUFF
ID_MINERAL = 150

# BUILDINGS
ID_NEXUS = 170
ID_TURRET = 171

# UNITS
ID_WORKER = 200
ID_RANGED = 201
ID_TANK = 202

